services:
  redis:
    image: redis:8-alpine
    container_name: grizgo-redis
    ports:
      - "6379:6379"
  cart-service:
    build:
      context: .
      dockerfile: CartService/Dockerfile
    container_name: grizgo-cart
    ports:
      - "5205:8080"
    environment:
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis