services:
  redis:
    image: redis:8-alpine
    container_name: grizgo-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4-management
    container_name: grizgo-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: grizgo
      RABBITMQ_DEFAULT_PASS: grizgo123

  cart-service:
    build:
      context: .
      dockerfile: CartService/Dockerfile
    container_name: grizgo-cart
    ports:
      - "5205:8080"
    environment:
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis
      - rabbitmq