services:
  delivery-db:
    image: postgres:16
    container_name: delivery-db
    environment:
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: delivery
      POSTGRES_DB: delivery
    ports:
      - "5432:5432"
    volumes:
      - delivery-db-data:/var/lib/postgresql/data

  delivery-api:
    build:
      context: ./Delivery.Api
      dockerfile: Dockerfile
    container_name: delivery-api
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - delivery-db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DeliveryDb: "Host=delivery-db;Port=5432;Database=delivery;Username=delivery;Password=delivery"

volumes:
  delivery-db-data:
