@UserService_HostAddress = https://localhost:7265

POST {{UserService_HostAddress}}/api/users/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "test123"
}

###

GET {{UserService_HostAddress}}/api/users/me
Authorization: Bearer PASTE_TOKEN_OVDE